// Blocked Items Data - Auto-generated January 22, 2026
// Source: JIRA API - Automated fetch
// DO NOT EDIT MANUALLY - This file is regenerated by scripts/fetch-jira-data.js

export interface BlockedItem {
  key: string;
  summary: string;
  assignee: string;
  daysBlocked: number;
  category: string;
  priority: "P0" | "P1" | "P2";
  jiraUrl: string;
  reason?: string;
}

// Current Sprint Blocked Items (4 items requiring immediate action)
export const sprintBlockedItems: BlockedItem[] = [
  {
    key: "BACK-1603",
    summary: "Deep Recon - DTCC Sync to DeepSee - extend data from additional fields to be imported from SFDC case",
    assignee: "Treven Trujillo",
    daysBlocked: 10,
    category: "client",
    priority: "P2",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1603"
  },
  {
    key: "UI-719",
    summary: "DeepRecon - Add To column to Actionable Data Pages (Accenture)",
    assignee: "Unassigned",
    daysBlocked: 22,
    category: "client",
    priority: "P1",
    jiraUrl: "https://deepsee.atlassian.net/browse/UI-719"
  },
  {
    key: "BACK-1489",
    summary: "Update classification-api Base Image to Ubuntu 24.04 LTS",
    assignee: "Unassigned",
    daysBlocked: 42,
    category: "infrastructure",
    priority: "P0",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1489"
  },
  {
    key: "BACK-1796",
    summary: "Automatically refresh the Allegro password before expiry",
    assignee: "Kannal Mutharasu",
    daysBlocked: 1,
    category: "artemis",
    priority: "P2",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1796"
  }
];

// All blocked items including backlog
export const blockedItems: BlockedItem[] = [
  {
    key: "BACK-1603",
    summary: "Deep Recon - DTCC Sync to DeepSee - extend data from additional fields to be imported from SFDC case",
    assignee: "Treven Trujillo",
    daysBlocked: 10,
    category: "client",
    priority: "P2",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1603"
  },
  {
    key: "UI-719",
    summary: "DeepRecon - Add To column to Actionable Data Pages (Accenture)",
    assignee: "Unassigned",
    daysBlocked: 22,
    category: "client",
    priority: "P1",
    jiraUrl: "https://deepsee.atlassian.net/browse/UI-719"
  },
  {
    key: "BACK-1489",
    summary: "Update classification-api Base Image to Ubuntu 24.04 LTS",
    assignee: "Unassigned",
    daysBlocked: 42,
    category: "infrastructure",
    priority: "P0",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1489"
  },
  {
    key: "BACK-1796",
    summary: "Automatically refresh the Allegro password before expiry",
    assignee: "Kannal Mutharasu",
    daysBlocked: 1,
    category: "artemis",
    priority: "P2",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1796"
  }
];

export const blockedSummary = {
  total: 4,
  sprintBlocked: 4,
  p0Count: 1,
  p1Count: 1,
  p2Count: 2,
  avgDaysBlocked: 19,
  oldestBlocked: "BACK-1489 (42 days)",
  unassignedCount: 2
};

export function getBlockedByPriority(priority: "P0" | "P1" | "P2"): BlockedItem[] {
  return blockedItems.filter(item => item.priority === priority);
}

export function getBlockedByAge(): BlockedItem[] {
  return [...blockedItems].sort((a, b) => b.daysBlocked - a.daysBlocked);
}

export function getCriticalBlocked(): BlockedItem[] {
  return blockedItems.filter(item => item.priority === "P0" || item.priority === "P1");
}

export function getBlockedByCategory(category: string): BlockedItem[] {
  return blockedItems.filter(item => item.category.includes(category));
}
