// Blocked Items Data - Auto-generated January 28, 2026
// Source: JIRA API - Automated fetch
// DO NOT EDIT MANUALLY - This file is regenerated by scripts/fetch-jira-data.js

export interface BlockedItem {
  key: string;
  summary: string;
  assignee: string;
  daysBlocked: number;
  category: string;
  priority: "P0" | "P1" | "P2";
  jiraUrl: string;
  reason?: string;
}

// Current Sprint Blocked Items (1 items requiring immediate action)
export const sprintBlockedItems: BlockedItem[] = [
  {
    key: "BACK-1796",
    summary: "Automatically refresh the Allegro password before expiry",
    assignee: "Kannal Mutharasu",
    daysBlocked: 6,
    category: "artemis",
    priority: "P2",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1796"
  }
];

// All blocked items including backlog
export const blockedItems: BlockedItem[] = [
  {
    key: "BACK-1796",
    summary: "Automatically refresh the Allegro password before expiry",
    assignee: "Kannal Mutharasu",
    daysBlocked: 6,
    category: "artemis",
    priority: "P2",
    jiraUrl: "https://deepsee.atlassian.net/browse/BACK-1796"
  }
];

export const blockedSummary = {
  total: 1,
  sprintBlocked: 1,
  p0Count: 0,
  p1Count: 0,
  p2Count: 1,
  avgDaysBlocked: 6,
  oldestBlocked: "BACK-1796 (6 days)",
  unassignedCount: 0
};

export function getBlockedByPriority(priority: "P0" | "P1" | "P2"): BlockedItem[] {
  return blockedItems.filter(item => item.priority === priority);
}

export function getBlockedByAge(): BlockedItem[] {
  return [...blockedItems].sort((a, b) => b.daysBlocked - a.daysBlocked);
}

export function getCriticalBlocked(): BlockedItem[] {
  return blockedItems.filter(item => item.priority === "P0" || item.priority === "P1");
}

export function getBlockedByCategory(category: string): BlockedItem[] {
  return blockedItems.filter(item => item.category.includes(category));
}
