// JIRA Metrics Data - Auto-generated January 30, 2026
// Source: JIRA API - Automated fetch
// DO NOT EDIT MANUALLY - This file is regenerated by scripts/fetch-jira-data.js

export interface JiraMetrics {
  lastUpdated: string;
  extractionSource: string;
  sprintInfo: {
    name: string;
    dates: string;
    daysRemaining: number;
    totalStoryPoints: number;
    avgVelocity: number;
    overCommitment: string;
  };
  overall: {
    totalActiveTickets: number;
    totalInProgress: number;
    totalToDo: number;
    totalCodeReview: number;
    totalBlocked: number;
    totalDone: number;
    totalWithStoryPoints: number;
  };
  storyPoints: {
    completed: number;
    inProgress: number;
    notStarted: number;
    completionRate: number;
  };
  engineerSummary: {
    activeEngineers: number;
    engineersWithNoTickets: string[];
    highestLoad: { name: string; tickets: number }[];
  };
  longRunningTickets: Array<{
    id: string;
    title: string;
    assignee: string;
    status: string;
    daysInStatus: number;
    warningLevel: 'critical' | 'warning' | 'normal';
    reason?: string;
  }>;
}

export const jiraMetrics: JiraMetrics = {
  lastUpdated: "January 30, 2026 at 8:37 AM MT",
  extractionSource: "JIRA API - 2026-S3",

  sprintInfo: {
    name: "2026-S3",
    dates: "Jan 30 - Feb 13, 2026",
    daysRemaining: 14,
    totalStoryPoints: 109,
    avgVelocity: 80,
    overCommitment: "36% over average velocity"
  },

  overall: {
    totalActiveTickets: 78,
    totalInProgress: 10,
    totalToDo: 61,
    totalCodeReview: 6,
    totalBlocked: 0,
    totalDone: 1,
    totalWithStoryPoints: 30
  },

  storyPoints: {
    completed: 5,
    inProgress: 38,
    notStarted: 66,
    completionRate: 5
  },

  engineerSummary: {
    activeEngineers: 11,
    engineersWithNoTickets: [],
    highestLoad: [
      { name: "Aleksander Winski", tickets: 3 },
      { name: "Kannal Mutharasu", tickets: 3 },
      { name: "Ivan Peev", tickets: 3 }
    ]
  },

  longRunningTickets: [
    {
      id: "BACK-1690",
      title: "Create data lifecycle management policies",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 24,
      warningLevel: "warning"
    },
    {
      id: "BACK-1693",
      title: "GPU resource allocation for LLM inference",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 24,
      warningLevel: "warning"
    },
    {
      id: "BACK-1694",
      title: "Create compute cost monitoring dashboard",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 24,
      warningLevel: "warning"
    },
    {
      id: "BACK-1699",
      title: "Webhook delivery and retry mechanism",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 24,
      warningLevel: "warning"
    },
    {
      id: "BACK-1700",
      title: "API Gateway rate limiting implementation",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 24,
      warningLevel: "warning"
    }
  ]
};

export interface EpicProgress {
  key: string;
  description: string;
  progress: number;
  status: 'not_started' | 'in_progress' | 'complete';
}

export const epicProgress: EpicProgress[] = [
  { key: "BACK-1650", description: "BACK-1650 - 3 tickets", progress: 0, status: 'in_progress' },
  { key: "PR-1562", description: "PR-1562 - 2 tickets", progress: 0, status: 'in_progress' },
  { key: "BACK-1234", description: "BACK-1234 - 2 tickets", progress: 0, status: 'in_progress' },
  { key: "BACK-1656", description: "BACK-1656 - 4 tickets", progress: 0, status: 'not_started' },
  { key: "BACK-1680", description: "BACK-1680 - 15 tickets", progress: 0, status: 'not_started' },
  { key: "UI-694", description: "UI-694 - 3 tickets", progress: 0, status: 'not_started' },
  { key: "BACK-1726", description: "BACK-1726 - 4 tickets", progress: 0, status: 'not_started' },
  { key: "BACK-1758", description: "BACK-1758 - 4 tickets", progress: 0, status: 'not_started' }
];

// Sprint Comparison Data - Historical data preserved, current sprint updated
export const sprintComparison = {
  s2: { sprint: "2026-S2", committed: 204, completed: 124, rate: 61, status: "in_progress" },
  s1: { sprint: "2026-S1", committed: 94, completed: 91, rate: 97, status: "complete" },
  s3: { sprint: "2026-S3", committed: 109, completed: 5, rate: 5, status: "in_progress" }
};
