// JIRA Metrics Data - Updated February 17, 2026
// Source: JIRA API - Sprint 2026-S4 (Day 1 of 14)
// DO NOT EDIT MANUALLY - This file is regenerated by scripts/fetch-jira-data.js

export interface JiraMetrics {
  lastUpdated: string;
  extractionSource: string;
  sprintInfo: {
    name: string;
    dates: string;
    daysRemaining: number;
    totalStoryPoints: number;
    avgVelocity: number;
    overCommitment: string;
  };
  overall: {
    totalActiveTickets: number;
    totalInProgress: number;
    totalToDo: number;
    totalCodeReview: number;
    totalBlocked: number;
    totalDone: number;
    totalWithStoryPoints: number;
  };
  storyPoints: {
    completed: number;
    inProgress: number;
    notStarted: number;
    completionRate: number;
  };
  engineerSummary: {
    activeEngineers: number;
    engineersWithNoTickets: string[];
    highestLoad: { name: string; tickets: number }[];
  };
  longRunningTickets: Array<{
    id: string;
    title: string;
    assignee: string;
    status: string;
    daysInStatus: number;
    warningLevel: 'critical' | 'warning' | 'normal';
    reason?: string;
  }>;
}

export const jiraMetrics: JiraMetrics = {
  lastUpdated: "February 17, 2026 at 12:00 PM MT",
  extractionSource: "JIRA API - 2026-S4",

  sprintInfo: {
    name: "2026-S4",
    dates: "Feb 13 - Feb 27, 2026",
    daysRemaining: 14,
    totalStoryPoints: 120,
    avgVelocity: 134,
    overCommitment: "Within range at 120 pts (avg 134)"
  },

  overall: {
    totalActiveTickets: 61,
    totalInProgress: 11,
    totalToDo: 41,
    totalCodeReview: 5,
    totalBlocked: 2,
    totalDone: 0,
    totalWithStoryPoints: 38
  },

  storyPoints: {
    completed: 0,
    inProgress: 43,
    notStarted: 72,
    completionRate: 0
  },

  engineerSummary: {
    activeEngineers: 14,
    engineersWithNoTickets: ["Darius Ouderkirk", "Loris D'Acunto", "Karolina Toman"],
    highestLoad: [
      { name: "Ivan Peev", tickets: 3 },
      { name: "Aleksander Winski", tickets: 3 },
      { name: "Matthew Snow", tickets: 3 }
    ]
  },

  longRunningTickets: [
    {
      id: "BACK-1921",
      title: "Mercury HITL - Capture Additional Context",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 0,
      warningLevel: "critical",
      reason: "Mercury HITL — Colony Bank dependency, UNASSIGNED"
    },
    {
      id: "UI-743",
      title: "Deep Recon - Make aggregated report exportable (Broadridge)",
      assignee: "Unassigned",
      status: "Blocked",
      daysInStatus: 0,
      warningLevel: "critical",
      reason: "Blocked AND unassigned — Broadridge client dependency"
    },
    {
      id: "UI-740",
      title: "Deep Recon - Add Dropdown List for Assignee Names",
      assignee: "Matthew Snow",
      status: "Blocked",
      daysInStatus: 0,
      warningLevel: "critical",
      reason: "Blocked — internal dependency"
    },
    {
      id: "BACK-1862",
      title: "Create duplicate project for Colony Bank RV loans",
      assignee: "Konnor Willison",
      status: "In Progress",
      daysInStatus: 0,
      warningLevel: "warning",
      reason: "Colony Bank — high priority"
    },
    {
      id: "BACK-1657",
      title: "[PARSER] PDF extraction for multi-page documents",
      assignee: "Aleksander Winski",
      status: "Waiting for Approval",
      daysInStatus: 0,
      warningLevel: "warning",
      reason: "Waiting for approval — 8 pts"
    }
  ]
};

export interface EpicProgress {
  key: string;
  description: string;
  progress: number;
  status: 'not_started' | 'in_progress' | 'complete';
}

export const epicProgress: EpicProgress[] = [
  { key: "BACK-1862", description: "Colony Bank RV Loans - 1 ticket", progress: 50, status: 'in_progress' },
  { key: "BACK-1918", description: "Colony GAP Coverage - 1 ticket", progress: 50, status: 'in_progress' },
  { key: "BACK-1921", description: "Mercury HITL - 6 tickets", progress: 0, status: 'not_started' },
  { key: "BACK-1532", description: "Sunwest Mercury - 2 tickets", progress: 0, status: 'not_started' },
  { key: "UI-755", description: "Broadridge Email - 1 ticket", progress: 50, status: 'in_progress' }
];

// Sprint Comparison Data - Historical data preserved, current sprint updated
export const sprintComparison = {
  s1: { sprint: "2026-S1", committed: 131, completed: 129, rate: 98, status: "complete" },
  s2: { sprint: "2026-S2", committed: 105, completed: 132, rate: 126, status: "complete" },
  s3: { sprint: "2026-S3", committed: 101, completed: 141, rate: 140, status: "complete" },
  s4: { sprint: "2026-S4", committed: 120, completed: 0, rate: 0, status: "in_progress" }
};
