// JIRA Metrics Data - Auto-generated January 22, 2026
// Source: JIRA API - Automated fetch
// DO NOT EDIT MANUALLY - This file is regenerated by scripts/fetch-jira-data.js

export interface JiraMetrics {
  lastUpdated: string;
  extractionSource: string;
  sprintInfo: {
    name: string;
    dates: string;
    daysRemaining: number;
    totalStoryPoints: number;
    avgVelocity: number;
    overCommitment: string;
  };
  overall: {
    totalActiveTickets: number;
    totalInProgress: number;
    totalToDo: number;
    totalCodeReview: number;
    totalBlocked: number;
    totalDone: number;
    totalWithStoryPoints: number;
  };
  storyPoints: {
    completed: number;
    inProgress: number;
    notStarted: number;
    completionRate: number;
  };
  engineerSummary: {
    activeEngineers: number;
    engineersWithNoTickets: string[];
    highestLoad: { name: string; tickets: number }[];
  };
  longRunningTickets: Array<{
    id: string;
    title: string;
    assignee: string;
    status: string;
    daysInStatus: number;
    warningLevel: 'critical' | 'warning' | 'normal';
    reason?: string;
  }>;
}

export const jiraMetrics: JiraMetrics = {
  lastUpdated: "January 22, 2026 at 2:51 PM MT",
  extractionSource: "JIRA API - 2026-S2",

  sprintInfo: {
    name: "2026-S2",
    dates: "Jan 16 - Jan 30, 2026",
    daysRemaining: 8,
    totalStoryPoints: 180,
    avgVelocity: 80,
    overCommitment: "125% over average velocity"
  },

  overall: {
    totalActiveTickets: 88,
    totalInProgress: 11,
    totalToDo: 38,
    totalCodeReview: 4,
    totalBlocked: 4,
    totalDone: 31,
    totalWithStoryPoints: 57
  },

  storyPoints: {
    completed: 62,
    inProgress: 39,
    notStarted: 79,
    completionRate: 34
  },

  engineerSummary: {
    activeEngineers: 12,
    engineersWithNoTickets: [],
    highestLoad: [
      { name: "Ivan Peev", tickets: 10 },
      { name: "Kannal Mutharasu", tickets: 8 },
      { name: "Darius Ouderkirk", tickets: 6 }
    ]
  },

  longRunningTickets: [
    {
      id: "BACK-1489",
      title: "Update classification-api Base Image to Ubuntu 24.04 LTS",
      assignee: "Unassigned",
      status: "Blocked",
      daysInStatus: 42,
      warningLevel: "critical"
    },
    {
      id: "UI-719",
      title: "DeepRecon - Add To column to Actionable Data Pages (Accenture)",
      assignee: "Unassigned",
      status: "Blocked",
      daysInStatus: 22,
      warningLevel: "warning"
    },
    {
      id: "BACK-1689",
      title: "Implement data partitioning strategy",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 16,
      warningLevel: "warning"
    },
    {
      id: "BACK-1691",
      title: "Kubernetes workload autoscaling configuration",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 16,
      warningLevel: "warning"
    },
    {
      id: "BACK-1692",
      title: "Implement agent container health monitoring",
      assignee: "Unassigned",
      status: "To Do",
      daysInStatus: 16,
      warningLevel: "warning"
    }
  ]
};

export interface EpicProgress {
  key: string;
  description: string;
  progress: number;
  status: 'not_started' | 'in_progress' | 'complete';
}

export const epicProgress: EpicProgress[] = [
  { key: "BACK-1234", description: "BACK-1234 - 3 tickets", progress: 67, status: 'in_progress' },
  { key: "BACK-1292", description: "BACK-1292 - 3 tickets", progress: 33, status: 'in_progress' },
  { key: "UI-694", description: "UI-694 - 8 tickets", progress: 25, status: 'in_progress' },
  { key: "BACK-1650", description: "BACK-1650 - 4 tickets", progress: 0, status: 'in_progress' },
  { key: "BACK-1232", description: "BACK-1232 - 4 tickets", progress: 0, status: 'in_progress' },
  { key: "BACK-1583", description: "BACK-1583 - 4 tickets", progress: 100, status: 'complete' },
  { key: "BACK-1656", description: "BACK-1656 - 4 tickets", progress: 0, status: 'not_started' },
  { key: "BACK-1680", description: "BACK-1680 - 7 tickets", progress: 0, status: 'not_started' },
  { key: "BACK-1704", description: "BACK-1704 - 4 tickets", progress: 0, status: 'not_started' }
];

// Sprint Comparison Data - Historical data preserved, current sprint updated
export const sprintComparison = {
  s2: { sprint: "2026-S2", committed: 180, completed: 62, rate: 34, status: "in_progress" },
  s1: { sprint: "2026-S1", committed: 94, completed: 91, rate: 97, status: "complete" }
};
