// Sprint Data - Auto-generated January 29, 2026
// Source: JIRA API - Automated fetch
// DO NOT EDIT MANUALLY - This file is regenerated by scripts/fetch-jira-data.js

export const EXTRACTION_TIMESTAMP = "2026-01-29T02:05:40.464Z";
export const DATA_SOURCE = "JIRA API - Automated";

export interface SprintStatus {
  toDo: number;
  blocked: number;
  inProgress: number;
  codeReview: number;
  done: number;
}

export interface SprintMix {
  artemis: number;
  client: number;
  infrastructure: number;
}

export interface Sprint {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  status: 'active' | 'planned' | 'future';
  totalTickets: number;
  completion: SprintStatus;
  completionRate: number;
  daysRemaining: number;
  likelyRollovers?: number;
  mix: SprintMix;
  assessment: 'artemis-focused' | 'balanced' | 'client-heavy';
}

export interface SprintItem {
  key: string;
  summary: string;
  category?: string;
  client?: string;
  staleDays?: number;
  blockedDays?: number;
  unassigned?: boolean;
  priority?: string;
  recommended?: boolean;
}

export interface NextSprintArtemisItem {
  key: string;
  summary: string;
  category: string;
}

export interface NextSprintClientItem {
  key: string;
  summary: string;
  client: string;
}

// Current Sprint Data - 2026-S2 (Active)
export const CURRENT_SPRINT: Sprint = {
  id: '2026-S2',
  name: 'Sprint 2026-S2',
  startDate: '2026-01-16',
  endDate: '2026-01-30',
  status: 'active',
  totalTickets: 96,
  completion: {
    toDo: 26,
    blocked: 1,
    inProgress: 13,
    codeReview: 4,
    done: 52
  },
  completionRate: 57,
  daysRemaining: 1,
  likelyRollovers: 26,
  mix: {
    artemis: 58,
    client: 35,
    infrastructure: 6
  },
  assessment: 'artemis-focused'
};

export const NEXT_SPRINT: Sprint = {
  id: '2026-S3',
  name: 'Sprint 2026-S3',
  startDate: '2026-01-30',
  endDate: '2026-02-13',
  status: 'planned',
  totalTickets: 40,
  completion: {
    toDo: 40,
    blocked: 0,
    inProgress: 0,
    codeReview: 0,
    done: 0
  },
  completionRate: 0,
  daysRemaining: 15,
  mix: {
    artemis: 50,
    client: 30,
    infrastructure: 20
  },
  assessment: 'artemis-focused'
};

export const FUTURE_SPRINT: Sprint = {
  id: 'Future',
  name: 'Sprint Future',
  startDate: '',
  endDate: '',
  status: 'future',
  totalTickets: 0,
  completion: { toDo: 0, blocked: 0, inProgress: 0, codeReview: 0, done: 0 },
  completionRate: 0,
  daysRemaining: 28,
  mix: { artemis: 60, client: 25, infrastructure: 15 },
  assessment: 'artemis-focused'
};

export const SPRINTS = [CURRENT_SPRINT, NEXT_SPRINT, FUTURE_SPRINT];
export const sprints = SPRINTS;
export const currentSprint = CURRENT_SPRINT;

// Next Sprint Planned Items
export const NEXT_SPRINT_ARTEMIS_ITEMS: NextSprintArtemisItem[] = [
  { key: 'BACK-1654', summary: '[MERCURY] BBVA - Term type extraction for reconciliation', category: 'artemis' },
  { key: 'BACK-1690', summary: 'Create data lifecycle management policies', category: 'artemis' },
  { key: 'BACK-1693', summary: 'GPU resource allocation for LLM inference', category: 'artemis' },
  { key: 'BACK-1694', summary: 'Create compute cost monitoring dashboard', category: 'artemis' },
  { key: 'BACK-1697', summary: 'MCP (Model Context Protocol) adapter', category: 'artemis' },
  { key: 'BACK-1699', summary: 'Webhook delivery and retry mechanism', category: 'artemis' },
  { key: 'BACK-1700', summary: 'API Gateway rate limiting implementation', category: 'artemis' },
  { key: 'BACK-1702', summary: 'Self-healing agent restart logic', category: 'artemis' },
  { key: 'BACK-1703', summary: 'Create platform health dashboard', category: 'artemis' },
  { key: 'BACK-1818', summary: 'Updates to Prediction API response', category: 'artemis' },
  { key: 'BACK-1819', summary: 'Update Project Names', category: 'artemis' },
  { key: 'CI-932', summary: 'Create Dev Namespace for POC/Artemis UI', category: 'artemis' }
];

export const NEXT_SPRINT_CLIENT_ITEMS: NextSprintClientItem[] = [
  { key: 'BACK-1795', summary: 'Add AccountName2 checklist item result to the Output (DTCC)', client: 'Back End Development' },
  { key: 'BACK-1828', summary: 'Deep Recon - Review the Counterparty extraction logic', client: 'Back End Development' },
  { key: 'BACK-1829', summary: 'Deep Recon - Add "contains" operator to filter for text inputs on Actionable Data page', client: 'Back End Development' },
  { key: 'BACK-1830', summary: 'Deep Recon - Make Due Date editable', client: 'Back End Development' },
  { key: 'BACK-1831', summary: 'Deep Recon - Add "cc" to json response (Accenture)', client: 'Back End Development' },
  { key: 'UI-749', summary: 'Deep Recon - Make Due Date editable on the UI', client: 'Front End Development' },
  { key: 'SC-326', summary: '[#PT34600_14] Access Control Issue in Actionable Data of DeepRecon', client: 'Security & Compliance' },
  { key: 'SC-327', summary: '[PT34600_15] Access Control Issue in Data Source of DeepRecon', client: 'Security & Compliance' },
  { key: 'SC-328', summary: '[#PT34600_16] Access Control Issue in Automation of DeepRecon', client: 'Security & Compliance' }
];

// Rollover candidates - High risk items that may not complete
export const ROLLOVER_HIGH_RISK: SprintItem[] = [
  { key: 'BACK-1644', summary: 'Finish Stories for Outlook Ingestion', category: 'ARTEMIS', staleDays: 12 },
  { key: 'BACK-1655', summary: '[MERCURY] API documentation and developer guide', category: 'ARTEMIS', staleDays: 7, unassigned: true },
  { key: 'BACK-1658', summary: '[PARSER] HTML structured file parsing for SEC filings', category: 'ARTEMIS', staleDays: 12, unassigned: true },
  { key: 'BACK-1661', summary: '[PARSER] Integration between Document Parser and Mercury Extraction', category: 'ARTEMIS', staleDays: 12, unassigned: true },
  { key: 'BACK-1722', summary: 'Deep Pilot - Improve Recalculation Performance', category: 'CLIENT', staleDays: 13 },
  { key: 'BACK-911', summary: 'Sources incorrectly removed from consideration for subgroup matching', category: 'ARTEMIS', staleDays: 12 },
  { key: 'BACK-1659', summary: '[PARSER] Automatic document type classification', category: 'ARTEMIS', staleDays: 1, unassigned: true },
  { key: 'UI-698', summary: 'Create "Recategorized By HITL" ', category: 'CLIENT', staleDays: 1, unassigned: true },
  { key: 'BACK-1663', summary: '[BLUEPRINT] Define data model and storage infrastructure', category: 'ARTEMIS', staleDays: 12, unassigned: true },
  { key: 'UI-719', summary: 'DeepRecon - Add To column to Actionable Data Pages (Accenture)', category: 'CLIENT', staleDays: 0, unassigned: true },
  { key: 'BACK-1489', summary: 'Update classification-api Base Image to Ubuntu 24.04 LTS', category: 'INFRASTRUCTURE', staleDays: 1, unassigned: true },
  { key: 'BACK-1530', summary: 'Setup BBVA Mercury Extraction Schema for Trade Fail Reconciliation', category: 'ARTEMIS', staleDays: 1, unassigned: true },
  { key: 'BACK-1532', summary: 'Fine-tune Mercury Extraction for Sunwest Bank Treasury Onboarding Project', category: 'ARTEMIS', staleDays: 0, unassigned: true },
  { key: 'BACK-1689', summary: 'Implement data partitioning strategy', category: 'ARTEMIS', staleDays: 22, unassigned: true },
  { key: 'BACK-1691', summary: 'Kubernetes workload autoscaling configuration', category: 'ARTEMIS', staleDays: 0, unassigned: true }
];

// Blocked Items in current sprint
export const BLOCKED_ITEMS: SprintItem[] = [
  { key: 'BACK-1796', summary: 'Automatically refresh the Allegro password before expiry', category: 'artemis', blockedDays: 7 }
];

// ARTEMIS Backlog Items
export const ARTEMIS_BACKLOG: SprintItem[] = [
  { key: 'BACK-846', summary: 'For Product OTC - 304288 While saving the annotation in XML system is throwing a error message “ There was a problem saving your feedback. “ ', priority: 'Blocker', recommended: true },
  { key: 'BACK-1048', summary: 'JPM - 600+ work items are not processing', priority: 'Blocker', recommended: true },
  { key: 'BACK-1281', summary: 'JPM - Unable to access DeepSee: "No healthy upstream."', priority: 'Blocker', recommended: true },
  { key: 'BACK-1399', summary: '30-50 minute delay between email received and created in DeepSee', priority: 'Blocker', recommended: true },
  { key: 'BACK-1400', summary: 'Email Replies not loading message details', priority: 'Blocker', recommended: true },
  { key: 'BACK-376', summary: 'Add sealed config for promethia__workflows to changing pod resource requests in vault', priority: 'Critical', recommended: true },
  { key: 'BACK-1096', summary: 'Duplicated inquiry ids in current_label_view', priority: 'Critical', recommended: true },
  { key: 'BACK-906', summary: 'Some \'Sent\' emails STILL getting Action Required added', priority: 'Critical', recommended: true },
  { key: 'PR-1559', summary: 'Document Classifier and Parser - Q1 2025', priority: 'Critical', recommended: true },
  { key: 'BACK-1620', summary: 'Implement Document Boundary Detection for Multi-Document Files', priority: 'Critical', recommended: true }
];

export const SPRINT_DATA_UPDATED = EXTRACTION_TIMESTAMP;

export function getSprintByStatus(status: 'active' | 'planned' | 'future'): Sprint | undefined {
  return SPRINTS.find(s => s.status === status);
}

export function formatSprintDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

export function getSprintMixChartData() {
  return [
    {
      sprint: `${CURRENT_SPRINT.name} (Current)`,
      ARTEMIS: CURRENT_SPRINT.mix.artemis,
      Client: CURRENT_SPRINT.mix.client,
      Infrastructure: CURRENT_SPRINT.mix.infrastructure
    },
    {
      sprint: `${NEXT_SPRINT.name} (Next)`,
      ARTEMIS: NEXT_SPRINT.mix.artemis,
      Client: NEXT_SPRINT.mix.client,
      Infrastructure: NEXT_SPRINT.mix.infrastructure
    },
    {
      sprint: `${FUTURE_SPRINT.name} (Future)`,
      ARTEMIS: FUTURE_SPRINT.mix.artemis,
      Client: FUTURE_SPRINT.mix.client,
      Infrastructure: FUTURE_SPRINT.mix.infrastructure
    }
  ];
}

export function formatDataTimestamp(isoString: string = EXTRACTION_TIMESTAMP): string {
  const date = new Date(isoString);
  return date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    timeZone: 'America/Denver'
  }) + ' MT';
}
