// MASTER_DATA_FEATURES - Auto-extracted from Excel
// Total Features: 74
// Generated: 2025-12-05
// Source: 2025-11-07-DeepSee-prioritization-dashboard-v3__4_.xlsx

export const MASTER_DATA_FEATURES = [
  {
    "id": "F-001",
    "name": "Mercury Extraction",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "Yes"
  },
  {
    "id": "F-002",
    "name": "Client Agent Interaction Enhancements",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "No"
  },
  {
    "id": "F-003",
    "name": "DeepSee Service Fabric Internal Enhancements",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Core Infrastructure",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "No"
  },
  {
    "id": "F-004",
    "name": "Retention Prediction UI",
    "bucket": "Make",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 3,
    "primaryClient": "BetaNXT",
    "additionalClients": "Broadridge",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "In Progress",
    "epicInJira": "No"
  },
  {
    "id": "F-005",
    "name": "Double-click to view dashboard messages",
    "bucket": "Make",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "Broadridge",
    "additionalClients": "Accenture, Broadridge",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "No"
  },
  {
    "id": "F-007",
    "name": "Matching Engine UI",
    "bucket": "Make",
    "agentType": "Matching Engine",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "Altaira",
    "additionalClients": "Avaloq, CTC, BBVA",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "No"
  },
  {
    "id": "F-008",
    "name": "Information Graph Enhanced Infrastructure",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Core Infrastructure",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "Yes"
  },
  {
    "id": "F-009",
    "name": "Enhanced Agent Outcome Reasoning and Planning",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "Yes"
  },
  {
    "id": "F-010",
    "name": "Inference / Training speed improvements",
    "bucket": "Don't Lose",
    "agentType": "Platform (All Agents)",
    "category": "Core Infrastructure",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "Yes"
  },
  {
    "id": "F-011",
    "name": "Activity Tracing Across Agents",
    "bucket": "Innovation",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-012",
    "name": "Exception Prediction",
    "bucket": "Innovation",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-013",
    "name": "Simplified Agentic UI Implementation",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-014",
    "name": "Information Graph UI Design",
    "bucket": "Innovation",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-015",
    "name": "MCP Integration with 3rd Party Agents",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "API Development",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-016",
    "name": "Enhanced Integration with 3rd Party Applications - Outlook & Ops Console",
    "bucket": "Don't Lose",
    "agentType": "Email Automation",
    "category": "API Development",
    "quarter": "NOW",
    "replicability": 4,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-017",
    "name": "User configurable dashboards",
    "bucket": "Don't Lose",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "Broadridge",
    "additionalClients": "Accenture, JPM, Avaloq, CTC, BBVA",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-018",
    "name": "Process Mapping and Optimization Opportunities",
    "bucket": "Innovation",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-019",
    "name": "Information Graph UI Implementation",
    "bucket": "Innovation",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-020",
    "name": "Technologist and Model Review UI implementation",
    "bucket": "Don't Lose",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-021",
    "name": "DeepSee Service Fabric External Enhancements",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Core Infrastructure",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "Yes"
  },
  {
    "id": "F-022",
    "name": "Integrated foreign language support",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 3,
    "primaryClient": "BBVA",
    "additionalClients": "Avaloq",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Yes",
    "prdStatus": "In Progress",
    "epicInJira": "Yes"
  },
  {
    "id": "F-023",
    "name": "Process variation highlights",
    "bucket": "Innovation",
    "agentType": "Platform (Analytics)",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-024",
    "name": "Agentic Card UI Implementation for 3rd Party Applications -Microsoft CoPilot",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-025",
    "name": "Enhanced Testing Suite UI Implementation",
    "bucket": "Don't Lose",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "Yes"
  },
  {
    "id": "F-026",
    "name": "DTCC Agent Onboarding - Trade Processing Phase 1",
    "bucket": "Make",
    "agentType": "Trade Processing",
    "category": "Client-Specific Work",
    "quarter": "NEXT",
    "replicability": 3,
    "primaryClient": "DTCC",
    "additionalClients": "0",
    "effortSize": "L-Large 8wks",
    "priorityTier": "Tier 1: Fast Track",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-027",
    "name": "DTCC Agent Onboarding - Trade Processing Phase 2",
    "bucket": "Make",
    "agentType": "Trade Processing",
    "category": "Client-Specific Work",
    "quarter": "NEXT",
    "replicability": 3,
    "primaryClient": "DTCC",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-028",
    "name": "DTCC Agent Onboarding - Core Reconciliation",
    "bucket": "Make",
    "agentType": "Core Reconciliation",
    "category": "Client-Specific Work",
    "quarter": "NEXT",
    "replicability": 3,
    "primaryClient": "DTCC",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-029",
    "name": "Trade Matching Engine Enhancement",
    "bucket": "Make",
    "agentType": "Matching Engine",
    "category": "Client-Specific Work",
    "quarter": "NEXT",
    "replicability": 2,
    "primaryClient": "Broadridge",
    "additionalClients": "Accenture, BBVA, CTC, Altaira, Avaloq",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-030",
    "name": "Email Automation Workflow",
    "bucket": "Make",
    "agentType": "Email Automation",
    "category": "Client-Specific Work",
    "quarter": "NOW",
    "replicability": 3,
    "primaryClient": "Broadridge",
    "additionalClients": "Accenture, BBVA, CTC, Altaira, Avaloq",
    "effortSize": "L-Large 8wks",
    "priorityTier": "Tier 1: Fast Track",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-031",
    "name": "Broadridge Critical Bug Fix - Email Processing",
    "bucket": "Don't Lose",
    "agentType": "Trade Processing",
    "category": "Bug Fixes",
    "quarter": "NOW",
    "replicability": 1,
    "primaryClient": "Broadridge",
    "additionalClients": "Accenture",
    "effortSize": "S-Small 2wks",
    "priorityTier": "Tier 0: Emergency",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-032",
    "name": "JP Morgan Monthly Reconciliation Enhancement",
    "bucket": "Don't Lose",
    "agentType": "Core Reconciliation",
    "category": "Client-Specific Work",
    "quarter": "LATER",
    "replicability": 3,
    "primaryClient": "JP Morgan",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-033",
    "name": "DTCC Settlements Optimization",
    "bucket": "Make",
    "agentType": "Security Settlements",
    "category": "Client-Specific Work",
    "quarter": "LATER",
    "replicability": 3,
    "primaryClient": "DTCC",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-034",
    "name": "Accenture Email Automation Deployment - HERA",
    "bucket": "Don't Lose",
    "agentType": "Email Automation",
    "category": "Client-Specific Work",
    "quarter": "NOW",
    "replicability": 4,
    "primaryClient": "Accenture",
    "additionalClients": "Broadridge",
    "effortSize": "L-Large 8wks",
    "priorityTier": "Tier 1: Fast Track",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-036",
    "name": "HMDA / CRA Reporting - Colony Bank",
    "bucket": "Make",
    "agentType": "HMDA / CRA",
    "category": "Client-Specific Work",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "Regional Banks",
    "additionalClients": "Colony Bank",
    "effortSize": "M-Medium 4wks",
    "priorityTier": "Tier 1: Fast Track",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-037",
    "name": "Treasury Agent Deployment - Sunwest Bank",
    "bucket": "Make",
    "agentType": "Standing Settlement Instructions",
    "category": "Client-Specific Work",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "Regional Banks",
    "additionalClients": "Sunwest Bank",
    "effortSize": "M-Medium 4wks",
    "priorityTier": "Tier 1: Fast Track",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-038",
    "name": "Vantage Bank Custom Reconciliation (POC)",
    "bucket": "Don't Lose",
    "agentType": "Core Reconciliation",
    "category": "Client-Specific Work",
    "quarter": "NEXT",
    "replicability": 2,
    "primaryClient": "Regional Banks",
    "additionalClients": "Vantage Bank",
    "effortSize": "XL-Extra Large 12wks+",
    "priorityTier": "Tier 1: Fast Track",
    "artemis": "No",
    "prdStatus": "Complete",
    "epicInJira": "Yes"
  },
  {
    "id": "F-039",
    "name": "Email Automation - Response Generation Enhancement",
    "bucket": "Make",
    "agentType": "Email Automation",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-040",
    "name": "Trade Processing - 100% Accuracy Validation",
    "bucket": "Make",
    "agentType": "Trade Processing",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "0",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-041",
    "name": "Security Settlements - Break Resolution Automation",
    "bucket": "Make",
    "agentType": "Security Settlements",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "Multiple",
    "additionalClients": "Altaira, Broadridge, BBVA, CTC, Avaloq",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-042",
    "name": "SSI - Real-time Data Validation",
    "bucket": "Make",
    "agentType": "Standing Settlement Instructions",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "Multiple",
    "additionalClients": "DTCC, CIBC",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-043",
    "name": "Matching Engine - External Break Detection",
    "bucket": "Make",
    "agentType": "Matching Engine",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 4,
    "primaryClient": "Multiple",
    "additionalClients": "Broadridge, BBVA, Avaloq, CTC",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-045",
    "name": "Loan Operations - Application Automation",
    "bucket": "Make",
    "agentType": "Loan Operations",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 4,
    "primaryClient": "Multiple",
    "additionalClients": "Colony Bank, Sunwest, ICCU",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-046",
    "name": "Core Reconciliation - Multi-System Support",
    "bucket": "Make",
    "agentType": "Core Reconciliation",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "Multiple",
    "additionalClients": "Colony Bank, Sunwest, ICCU",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "No",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-059",
    "name": "Document Parser to identify multiple docs in a single file from Financial Services Content to highlight Context Mining, Parse multiple files and Classify them)",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-048",
    "name": "Ingest Email / Case (Outlook, GMAIL, ServiceNow, Salesforce, Dyanmics)",
    "bucket": "Make",
    "agentType": "DeepRecon",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "Multiple",
    "additionalClients": "Broadridge, Accenture, BBVA, Avaloq, CTC, Altaira",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-049",
    "name": "Ingest Content (Attachment, SharePoint, SFTP, API Call)",
    "bucket": "Make",
    "agentType": "DeepPilot",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-050",
    "name": "Success / Failure and Retry of Ingestion Message",
    "bucket": "Don't Lose",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-051",
    "name": "Summary Extraction for Initial BluePrint Messaging",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-052",
    "name": "Email Parsing and Normalization",
    "bucket": "Make",
    "agentType": "DeepRecon",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-053",
    "name": "Ingestion of and Execution of Blueprint",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-054",
    "name": "Classification of Email Message",
    "bucket": "Make",
    "agentType": "DeepRecon",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-055",
    "name": "Determination of Follow-on Process from Request",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-056",
    "name": "Link to follow on Action (Agent/ API Call / Email Response)",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-057",
    "name": "Plan to generate Outcome from data",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-058",
    "name": "Call System for Additional Required Data (Form Message / Send / Receive) to generate Work Item",
    "bucket": "Make",
    "agentType": "DeepRecon",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-060",
    "name": "Deep Content Extraction - Implementation of F-001 in ARTEMIS",
    "bucket": "Make",
    "agentType": "DeepPilot",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-061",
    "name": "Application of Business Logic from Process Map",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-062",
    "name": "Reconciliation across all sources to find internal mismatches primarily system to content",
    "bucket": "Make",
    "agentType": "DeepPilot",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-064",
    "name": "Capture HITL feedback for extraction",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-065",
    "name": "Capture HITL feedback to correct outcome",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-066",
    "name": "Incorporate HITL feedback to adjust outcome",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-067",
    "name": "Incorporate HITL feedback to adjust business logic and update blueprint",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-068",
    "name": "Highlight exceptions per checklist item (Missing Document, Missing Extracted term, Break, Flag for followup, Pending user feedback, pending other agent, Pending system)",
    "bucket": "Make",
    "agentType": "DeepPilot",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-069",
    "name": "Summary of Agent's work including version of Agent, model, logic",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-070",
    "name": "Generate and transmit system updates and payloads",
    "bucket": "Make",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-071",
    "name": "Track success of messages both outgoing and expected responses",
    "bucket": "Don't Lose",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-072",
    "name": "Incorporates incoming messages and routes them for email responses",
    "bucket": "Make",
    "agentType": "DeepRecon",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-074",
    "name": "DeepGraph which captures all knowledge associated with these work items to feed insights and better response",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-075",
    "name": "DeepGraph Suggestions ",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-076",
    "name": "DeepPilot - Dashboards",
    "bucket": "Make",
    "agentType": "DeepPilot",
    "category": "Platform Improvements",
    "quarter": "NEXT",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-077",
    "name": "Ability to Create on demand Dashboards from DeepSee Information Graph",
    "bucket": "Don't Lose",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-078",
    "name": "Web Scraping Tool (Includes Login, Access Data, Structuring, and Use in Work item). Note: Could be ACI",
    "bucket": "Make",
    "agentType": "DeepPilot",
    "category": "Platform Improvements",
    "quarter": "LATER",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-079",
    "name": "Agent Library and BluePrint Selection (Includes Categories,Terms, Schema, Checklist Items)",
    "bucket": "Innovation",
    "agentType": "Platform (All Agents)",
    "category": "Platform Improvements",
    "quarter": "NOW",
    "replicability": 5,
    "primaryClient": "All",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  },
  {
    "id": "F-080",
    "name": "Watchtower News Feed v1",
    "bucket": "Innovation",
    "agentType": "WATCHTOWER",
    "category": "Client-Specific Work",
    "quarter": "NEXT",
    "replicability": 1,
    "primaryClient": "Altaira",
    "additionalClients": "",
    "effortSize": "",
    "priorityTier": "Tier 4: Backlog",
    "artemis": "Unknown",
    "prdStatus": "Not Started",
    "epicInJira": "No"
  }
];

// BUCKET SUMMARY
export const BUCKET_SUMMARY = {
  "Make": 45,
  "Innovation": 17,
  "Don't Lose": 12
};

// QUARTER SUMMARY
export const QUARTER_SUMMARY = {
  "NOW": 40,
  "NEXT": 22,
  "LATER": 12
};

// AGENT TYPE SUMMARY
export const AGENT_TYPE_SUMMARY = {
  "Platform (All Agents)": 31,
  "Platform (Analytics)": 10,
  "DeepPilot": 6,
  "DeepRecon": 5,
  "Email Automation": 4,
  "Core Reconciliation": 4,
  "Trade Processing": 4,
  "Matching Engine": 3,
  "Security Settlements": 2,
  "Standing Settlement Instructions": 2,
  "HMDA / CRA": 1,
  "Loan Operations": 1,
  "WATCHTOWER": 1
};
